import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { Document, NodeIO } from '@gltf-transform/core';
import { Validators, ValidationIssueSeverity } from '3d-tiles-validator';
import { describe, expect, it } from 'vitest';

import { repairTileset, validateTileset, writeTileset } from './tilesetIntegrity.js';

/** 3d-tiles-validator (CesiumGS) is a real dev-dependency, not a stand-in -- it pulls in
 * `cesium` + `sharp` (native image bindings), which is heavier than this repo's other
 * dev-dependencies and has a real chance of hitting a CI image without sharp's prebuilt
 * binary for its platform/libc. Rather than silently letting that manifest as a flaky/red
 * pipeline, it's an explicit opt-out: set SKIP_3D_TILES_VALIDATOR=true to skip this file
 * entirely. Confirmed working locally against 3d-tiles-validator 0.6.1 on Node 24/win32 as of
 * this writing -- flip the env var (in CI config, not here) if a future CI image can't
 * install sharp. */
const skip = process.env['SKIP_3D_TILES_VALIDATOR'] === 'true';

async function makeTempDir(): Promise<string> {
  return fsp.mkdtemp(path.join(os.tmpdir(), 'plantscope-tileset-validator-'));
}

async function writeTestGlb(glbPath: string, offset: [number, number, number] = [0, 0, 0]): Promise<void> {
  const doc = new Document();
  const buffer = doc.createBuffer();
  const [ox, oy, oz] = offset;
  const positions = new Float32Array([ox, oy, oz, ox + 2, oy, oz, ox, oy + 2, oz]);
  const indices = new Uint16Array([0, 1, 2]);
  const positionAccessor = doc.createAccessor('positions').setType('VEC3').setArray(positions).setBuffer(buffer);
  const indexAccessor = doc.createAccessor('indices').setType('SCALAR').setArray(indices).setBuffer(buffer);
  const primitive = doc.createPrimitive().setAttribute('POSITION', positionAccessor).setIndices(indexAccessor);
  const mesh = doc.createMesh('Triangle').addPrimitive(primitive);
  const node = doc.createNode('Triangle').setMesh(mesh);
  doc.createScene('Scene').addChild(node);
  await new NodeIO().write(glbPath, doc);
}

function errorIssues(result: Awaited<ReturnType<typeof Validators.validateTilesetFile>>) {
  return result.issues.filter((i) => i.severity === ValidationIssueSeverity.ERROR);
}

describe.skipIf(skip)('repaired/valid tileset.json conforms to the real OGC 3D Tiles spec (3d-tiles-validator)', () => {
  it('a tileset regenerated by repairTileset() from a broken (missing-content) original passes with zero validator errors', async () => {
    const dir = await makeTempDir();
    try {
      await writeTestGlb(path.join(dir, 'good-a.glb'), [0, 0, 0]);
      await writeTestGlb(path.join(dir, 'good-b.glb'), [100, 0, 0]);
      // Mirrors the real-world failure mode from prior client-file testing: tileset.json
      // references more content than actually exists on disk.
      await writeTileset(dir, {
        root: {
          children: [
            { content: { uri: 'good-a.glb' } },
            { content: { uri: 'good-b.glb' } },
            { content: { uri: 'missing-c.glb' } },
          ],
        },
      });

      await repairTileset(dir);
      const validation = await validateTileset(dir);
      expect(validation.ok).toBe(true);

      const result = await Validators.validateTilesetFile(path.join(dir, 'tileset.json'));
      const errors = errorIssues(result);
      expect(errors, JSON.stringify(errors, null, 2)).toEqual([]);
    } finally {
      await fsp.rm(dir, { recursive: true, force: true });
    }
  });

  it('a never-broken tileset (repair does not fire) also passes with zero validator errors', async () => {
    const dir = await makeTempDir();
    try {
      await writeTestGlb(path.join(dir, 'only.glb'));
      await writeTileset(dir, {
        asset: { version: '1.1' },
        geometricError: 10,
        root: {
          boundingVolume: { box: [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0.001] },
          geometricError: 0,
          refine: 'ADD',
          content: { uri: 'only.glb' },
        },
      });

      const validation = await validateTileset(dir);
      expect(validation.ok).toBe(true);

      const result = await Validators.validateTilesetFile(path.join(dir, 'tileset.json'));
      const errors = errorIssues(result);
      expect(errors, JSON.stringify(errors, null, 2)).toEqual([]);
    } finally {
      await fsp.rm(dir, { recursive: true, force: true });
    }
  });
});
